### PR TITLE
Well, that turned into a whole rewrite!

### PR DESCRIPTION
**Pull request by daveverwer**
The main purpose of this PR is to let SPI be the source of truth on whether a package is added rather than the package list JSON. It now queries for the status of the package page on SPI before deciding which version of the box to display.

Also modernised the JavaScript in a few places and simplified where I could.

### CODE REVIEW

**Comment by daveverwer** [comment]
One small bug. It doesn't cope with archived repositories:

https://github.com/SwiftyTesseract/libtesseract

I'm not even sure whether it should or not, but it's telling that I was trying to visit the SPI page for this repository and mourned the lack of a button.

**Comment by Sherlouk** [comment]
I have not tested what you've written here, but it all makes sense to me. Would be happy to run with it and give it a shot 👍

**Comment by daveverwer** [comment]
Sounds good. I'm also running it, let's see how it goes for a week or two but it's working well so far.

**Comment by Sherlouk** [comment]
Was an issue before, but still has problems if you navigate to a link from https://github.com/trending/swift it won't detect the package because it doesn't think it's a repository.

**Comment by daveverwer** [comment]
> Was an issue before, but still has problems if you navigate to a link from https://github.com/trending/swift it won't detect the package because it doesn't think it's a repository.

That's very weird. Isn't it just a normal repository they're linking to?

**Comment by daveverwer** [comment]
I think this is a page reload thing. If I navigate from trending to a repository I get no box, but refreshing the page then brings the box in. I bet there's no page reload event from that trending page. We may need to hook into an event rather than just running the code from the root of the script.

**Comment by Sherlouk** [comment]
Done a bunch of testing and working well for me - definitely not worse than main.

**Pull request merged**
